# Generated by Django 6.0.3 on 2026-03-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteennear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='menu',
            field=models.TextField(default='Нет информации о меню'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='canteen',
            name='working_hours',
            field=models.CharField(default='Нет информации о графике работы', max_length=200),
            preserve_default=False,
        ),
    ]
