# Generated by Django 6.0.3 on 2026-03-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteennear', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canteen',
            name='city',
        ),
    ]
